export const CHAT_CHANNELS_PROVIDER_TOKEN = 'CHAT_CHANNELS_PROVIDER_TOKEN';
export const MESSAGES_PROVIDER_TOKEN = 'MESSAGES_PROVIDER_TOKEN';
export const CHAT_CHANNELS_COLLECTION = 'chat_channels';
export const MESSAGES_COLLECTION = 'messages'; 