export const LANDING_PAGE_CONFIGS_PROVIDER_TOKEN = 'LANDING_PAGE_CONFIGS_PROVIDER_TOKEN';
export const LANDING_PAGE_CONFIGS_COLLECTION = 'landing_page_config';
export const APP_CONFIGS_COLLECTION = 'app_configs';
export const APP_CONFIGS_PROVIDER_TOKEN = 'APP_CONFIGS_PROVIDER_TOKEN';